# 예외처리



## 개요

- 디버깅
- 에러와 예외
- 예외처리
- 예외 발생 시키기



### ‘어느 부분을 중점적으로 봐야할까?’

- 제어되는시점, 조건/반복, 함수

1. Syntax Error
2. 이러이러한 것들

- branches: 모든 조건이 원하는대로 동작하는지
- for loops: 반복문 진입 여부, 원하는 횟수
- while loop: for loops와 동일, 종료조건 동작
- function: 함수 호출 시, 함수 파라미터, 결과



## 디버깅

“코드 상태를 신중하게 출력해가며 심사숙고하는 것보다 효과적인 디버깅 도구는 없습니다.”

- 브라이언 커니핸, Unix for Beginners.
- print 함수 활용
  - 특정 함수 결과, 반복조건 결과 등 나눠서 생각
  - 코드를 bisection으로 나눠서 생각
- 개발 환경(text editor, IDE) 등에서 제공하는 기능 활용
  - breakpoint, 변수 조회 등
- Python tutoe 활용 (단순 파이썬 코드인 경우)
- 뇌컴파일, 눈디버깅



### 코드를 작성하다가...

- 에러메시지 발생 시 해당하는 위치를 찾아 해결
- 로직 에러 박생 시
  - 명시적인 에러 메시지 없이 예상과 다른 결과가 나온 경우
    - 정상적으로 동작하였던 코드 이후 작성된 코드를 생각해봄
    - 전체 코드를 살펴봄
    - 휴식을 가져봄 ㅋㅋㅋ
    - 누군가에게 설명해봄
  - 러버덕 디버깅: 작은 오리를 두고 얘한테 설명하면서 디버깅
  - 고맙다! 에러메시지야!



### 문법 에러 (Syntax Error)

- 신탁스 에러, 실행 자체가 안 됨
- 파일이름, 줄번호, ^ 문자를 통해 파이썬이 코드를 읽어 나갈 때 (parser)문제가 발생한 위치를 표현
- 줄에서 에러가 감지된 가장 앞ㅍ의 위치를 가리키는 캐럿(caret)기호(^) 표시

- ![img](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/75863582-219d-44fb-b3ab-363d5a7010c1/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T102941Z&X-Amz-Expires=86400&X-Amz-Signature=26197ae9f4acdaebd295dba7d94653aa75844ce0de556afa8fea67dc9170bef8&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)Invalid Syntax : 유효하지 않은

![img](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/f8c8eca3-dca6-4aeb-895d-a49d4862c2c9/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T102954Z&X-Amz-Expires=86400&X-Amz-Signature=53393be2f062c8a5de5987d0c52036e63eadbc65fb628674aeaebf5a2192bcf4&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

- assign to literal :

![img](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/a7d226cb-e4ad-4a82-ad7d-90ff7acd77e7/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103009Z&X-Amz-Expires=86400&X-Amz-Signature=6cd405e86010cad5e2eee61fba59aa4bc0c099cf29270999f29716916a3d9a3c&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

- EOL (End of Line)

  라인이 안끝나

  ![img](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/fe6cf700-d0d9-4753-a174-d99f2eda63fb/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103021Z&X-Amz-Expires=86400&X-Amz-Signature=0b8d6c104e033f8c86cfc52e0c62874b317752f6cfa34c593ed6f0c80148dd81&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

- EOF (end of File) - 괄호 안닫았을때

  

### 예외 (Exception)

- 실행 도중 예상치 못한 상황을 맞이하면, 프로그램 실행을 멈춤
  - 문장 혹은 표현식이 **문법적으로 올바르더라도 발생**하는 에러
- 실행 중에 감지되는 에러들을 예외라고 부름
- 예외는 여러 타입으로 나타나고, 타입이 메시지의 일부로 출력됨
  - NameError, TypeError 등은 발생한 예외 타입의 종류(이름)
- 모든 내장 예외는 Exception Class 를 상속받아 이뤄짐
- 사용자 정의 예외를 만들어 관리할 수 있음



### ZeroDivisionError

0으로 나누려 했다

### NameError

실제 변수 이름이 없을 때 (오타를 냈거나)

### TypeError

여기저기서 발생

연산 자체가 불가능

타입 불일치 - 1 + ‘1’

- **argument 누락**

```python
divmod( )
import random
random.sample()
```

- **argument 개수 초과**

```python
divmod(1, 2, 3)
import random
random.sample(range((3), 1, 2)
```

- **argument type 불일치**

```python
import random
random.sample(1, 2)
```

### ValueError

타입은 올바르나 값이 적절하지 않거나 없는 경우

### IndexError

인덱스가 존재하지 않거나 범위를 벗어나는 경우

```python
empty_list = []
empry_list[2]
```

### KeyError

해당 키가 존재하지 않는 경우

```python
song = {'IU' : "좋은날"}
song['BTS']
```

### ModuleNotFoundError

존재하지 않는 모듈을 import한 경우

### ImportError

모듈은 있으나 존재하지 않는 클래스/함수를 가져오는 경우

### KeyboardInterrupt

임의로 프로그램 종료했을 때

```python
while True:
	continue
```

### IndentationError

들여쓰기가 적절하지 않는 경우

```python
for i in range(3):
print(i)
		 print(i)
```

## 파이썬 내장 예외 (Built-in-exceptions)

파이썬 3.10 이후로 좀 다르긴 한데, 3.9 버전으로 보자

### 파이썬 내장 예외의 클래스 계층 구조

![img](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/6df0c18e-4224-4624-b106-2aafb4242c81/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103439Z&X-Amz-Expires=86400&X-Amz-Signature=022381a50ceebd543c6d181b44a737676b8f485ee77e8c7148011ebb751a0ef3&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

# 예외처리

- try 문(statement) / except 절 (clause)을 이용하여 예외처리 가능

```python
try:
    try-명령문
except 예외:
    예외처리 명령문
else:
    else 명령문
Finally:
    최종 정리문 (clean-up)
```

- 주의: try문은 반드시 한 개 이상의 except 문이 필요



```python
num = input('숫자 입력: ')
print(int(num))
# a를 입력하면, ValueError 발생

try:
	num = input('숫자 입력: ')
	print(int(num))
except ValueError:
	print('숫자가 입력되지 않았습니다.')
```



### 에러 메시지 처리 (as)

- as 키워드를 활용하여 원본 에러 메시지를 사용할 수 있음(예외를 다른 이름에 대입)

```python
try:
	num = input('숫자 입력: ')
	print(int(num))

except ValueError as e:
	print(f'{e}, 숫자가 입력되지 않았습니다.')
```

여러개로

![Untitled.png (425×96)](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/99b351bf-58d9-4d34-8448-d91238d27950/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103737Z&X-Amz-Expires=86400&X-Amz-Signature=f21cc1ac9f2182ec1917c74b0abcea67575bf463368f6e23d0250f155385a0b9&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)

각각 나눠서

![Untitled.png (435×150)](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/6c667599-f082-4629-a12d-3f613c7ab783/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103747Z&X-Amz-Expires=86400&X-Amz-Signature=f3f19a063d43e2be6f796dfb22b820204f8723924029146df6a79b79dca788e7&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)



가장 큰 범주 위에 넣어버리면 거기서 다 걸리니까 가장 작은 범주부터 밑으로 내려서 순차적으로 처리하도록 만들기!!



- try : 코드를 실행함
- except : try 문에서 예외 발생 시 실행
- else : try 문에서 예외 발생하지 않으면 실행
- finally : 예외발생여부와
- 파일을 열고 읽는 코드를 작성할 때
  - 파일 열기 시도
    - 파일 없음 : ‘해당 파일이 없습니다.’ 출력 (except)
    - 파일 있음 : 파일 내용 출력 (else)
  - 해당 파일 읽기 작업 종료 메시지 출력 (finally)

![Untitled.png (642×230)](https://s3.us-west-2.amazonaws.com/secure.notion-static.com/edf01dde-d850-45f7-bc9e-2ac3369f4276/Untitled.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAT73L2G45EIPT3X45%2F20220202%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Date=20220202T103802Z&X-Amz-Expires=86400&X-Amz-Signature=003b4cade799f240500ede39c45aa1e2e66ca49d2117958735509afac01327db&X-Amz-SignedHeaders=host&response-content-disposition=filename%20%3D%22Untitled.png%22&x-id=GetObject)



**굳이 if else를 안쓰고 try excetp를 하는 이유는?**

- if else는 오류 발생하지 않으면 멈추겠죠
- 그러나 try except는 해당하는 예외에 해당하는 상황들을 조금 더 예외를 발생시키지 않고 처리할 수 잇다...

파이썬 스는 사람이 에러를 보고 해결타 개발자들이 다른 오픈소스를 볼 때

개발자들을 위한 SW 만들 때 모든 에러에 대한 상황들을 이야기 해줘야 함

사용자정의에러 파트도 있는데, 에러를 직접 만들어서 raise할 수도 있음



### raise (statement)

raise를 통해 예외를 강제로 발생

```python
raise <표현식>(메시지)
```

- 표현식에 예외 타입 지정 (주어지지 않을 경우 현재 스코프에서 활성화된 마지막 예외를 다시 일으킴)



### assert (statement)

```python
assert <표현식>(메시지)
```

- assert를 통해 예외 강제 발생
- 상태 검증에 사용되며, 표현식이 False이면 AssertionError
- 일반적인 **디버깅 용도** 로 사용



### raise vs assert

- raise : 실제 프로덕션 코드에서 활용 (강제로 에러 이름을 넣고 발생시킴)

- assert : 특정 조건이 실제로 false인 경우 발생. 디버깅, 테스트에서 활용

  -O 옵션으로 실행 시, assert문과 **debuf**에 따른 조건부 코드를 제거 후 실행